### ISSUE TITLE
unrelated question

### ISSUE THREAD

**Issue by francium** [ownaginatious/dotfiles#1]
Hi Dillon,

I had a unrelated question to your dotfiles. I couldn't find your email anywhere, so I thought this might be the only way I could reach you.

I've been using timetable generator for a while now and it's a fantastic tool. My question is, how are you parsing that data? You've graduated so I can't imagine you have access to mosaic directly. I took a look to see if maybe mosaic makes a request to get some json or other blob or data, but I couldn't see anything useful.
I noticed the 2018/2019 data are available literally within hours of it being available last week, so you've awesome got a pretty awesome system in place to get that data.

You can delete this issue and email me directly at [my_username][at][my_username][dot][cc] if you wish.

**Comment by ownaginatious** [comment]
Gonna close this one and respond via email.
